---

preset: symfony

enabled:
  - combine_consecutive_unsets
  - linebreak_after_opening_tag
  - no_short_echo_tag
  - ordered_imports
  - phpdoc_order
  - php_unit_construct
  - php_unit_dedicate_assert
  - long_array_syntax

finder :
  name    : [ "*.php", "*.twig" ]
  exclude : [ "vendor", "var" ]
  path    : [ "./" ]

...
