<?php

/*
 * This file is part of the `liip/LiipImagineBundle` project.
 *
 * (c) https://github.com/liip/LiipImagineBundle/graphs/contributors
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace Liip\ImagineBundle\Binary\Locator;

use Liip\ImagineBundle\Exception\Binary\Loader\NotLoadableException;
use Symfony\Component\AssetMapper\AssetMapperInterface;

/**
 * Resolves asset paths using the Symfony AssetMapper component.
 *
 * In a development environment, AssetMapper serves assets from their source directories (typically `/assets`)
 * without versioning. However, Twig's `asset()` helper generates public paths that include version hashes.
 * Since these versioned files do not physically exist on disk during development, this locator is used
 * to map the requested public versioned path back to the actual source file on the filesystem.
 *
 * In production, AssetMapper compiles and copies assets to the public directory with their version hashes
 * included in the filenames. Consequently, this locator is no longer necessary as the files exist at
 * their versioned paths.
 */
class AssetMapperLocator implements LocatorInterface
{
    public function __construct(
        private AssetMapperInterface $assetMapper,
    ) {
    }

    /**
     * Locates the physical source file for a given public asset path.
     *
     * This method iterates through all registered assets in the AssetMapper to find a match
     * for the provided public path (which may contain a version hash). If a match is found,
     * it returns the absolute path to the original source file.
     *
     * Inspired by Symfony's AssetMapper component @see https://github.com/symfony/asset-mapper/blob/7.3/AssetMapperDevServerSubscriber.php#L179.
     *
     * @param string $path the public path of the asset (e.g., as generated by Twig's asset() helper)
     *
     * @throws NotLoadableException if the public path cannot be resolved to a source asset
     *
     * @return string the absolute path to the source asset file
     */
    public function locate(string $path): string
    {
        $path = '/'.mb_ltrim($path, '/');
        foreach ($this->assetMapper->allAssets() as $assetCandidate) {
            if ($path === $assetCandidate->publicPath) {
                return $assetCandidate->sourcePath;
            }
        }
        throw new NotLoadableException(\sprintf('Asset with public path "%s" not found.', $path));
    }
}
