name: PHPStan

on:
  pull_request:
  push:
    branches:
      - 1.x
      - 2.x

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Update project dependencies
        uses: ramsey/composer-install@v2

      - name: Add vips
        run: composer require rokka/imagine-vips

      - name: Add asset mapper
        run: composer require symfony/asset-mapper

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze
